### ISSUE TITLE
Crash after error in PoGo

### ISSUE THREAD

**Issue by PrincessLune** [igoticecream/Snorlax#10]
Once in a while I get an in game in which the Pokemon I selected to catch vanishes from my screen, the pink box at the top shows up saying ERROR and your system notifications upon encounter fail. Here is the relevant time span in Xposed logs. 

```
10-01 03:51:22.831 E/Xposed  (19395): java.lang.ArrayIndexOutOfBoundsException: length=151; index=-1
```

10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b$a.m(SourceFile:263)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.b.a.a(SourceFile:143)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.b.a.a(SourceFile:107)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.b.a.a(SourceFile:90)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.b.c.a(Unknown Source)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.e.b.a(SourceFile:39)
10-01 03:51:22.831 E/Xposed  (19395):   at d.f.a.a(SourceFile:134)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.n$e.a(SourceFile:514)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.n$e.b(SourceFile:469)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.n$e.a(SourceFile:247)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.n$e.a(SourceFile:148)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.i$a.a(SourceFile:77)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.e$a.a(SourceFile:76)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.d$a.a(SourceFile:101)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.j$2.a(SourceFile:120)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.o$b.f(SourceFile:587)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.o$b.a(SourceFile:285)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.n$e.a(SourceFile:398)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.n$e.a(SourceFile:358)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.n$c.a(SourceFile:849)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.i$a.a(SourceFile:77)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.e$a.a(SourceFile:76)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.m$a.a(SourceFile:69)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.g$b.f(SourceFile:403)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.a.g$b.a(SourceFile:336)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.c.s.a(Unknown Source)
10-01 03:51:22.831 E/Xposed  (19395):   at d.d.e.b.a(SourceFile:39)
10-01 03:51:22.831 E/Xposed  (19395):   at d.f.a.a(SourceFile:134)
10-01 03:51:22.831 E/Xposed  (19395):   at com.b.b.c$a.a(SourceFile:208)
10-01 03:51:22.831 E/Xposed  (19395):   at com.b.b.a.a(SourceFile:47)
10-01 03:51:22.831 E/Xposed  (19395):   at com.b.b.d.a(SourceFile:84)
10-01 03:51:22.831 E/Xposed  (19395):   at com.b.b.e.a(SourceFile:20)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.c.m.a(SourceFile:70)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.c.k.b(SourceFile:105)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.c.d.a(SourceFile:99)
10-01 03:51:22.831 E/Xposed  (19395):   at com.icecream.snorlax.module.b.c.d.available(SourceFile:86)

**Comment by igoticecream** [comment]
Closing this issue as i seen over xda snorlax's thread you solved it.

**Comment by PrincessLune** [comment]
I'm sorry but that wasn't me on xda.. I don't know what that post was in reference to but it has nothing to do with snorlax crashing on an in game error. If I had solved my issue I would have closed this myself. I believe the first line of the copied log has great bearing on this issue

java.lang.ArrayIndexOutOfBoundsException: length=151; index=-1
