### ISSUE TITLE
Notifications fail after PoGo Error

### ISSUE THREAD

**Issue by PrincessLune** [igoticecream/Snorlax#11]
Sorry to have to reopen this, user exodius48 on XDA clearly was referring to their own issue thread closed 4 days hence. Late to the party, at least they showed..

To reiterate with a little more detail. Once in a while I get an in game in which the Pokemon I selected to catch vanishes from my screen, the pink box at the top shows up saying ERROR and your system notifications upon encounter fail. It appears to be happening when the pokemon are spawning at <5 sec. before despawn, so when I select them the server communicates back that there is no pokemon there and client-side it throws a "pokemon 151" error, for lack of a better term.

Here is the relevant time span in Xposed logs:

10-01 03:51:22.831 E/Xposed  (19395): java.lang.ArrayIndexOutOfBoundsException: length=151; index=-1
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b$a.m(SourceFile:263)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.b.a.a(SourceFile:143)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.b.a.a(SourceFile:107)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.b.a.a(SourceFile:90)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.b.c.a(Unknown Source)
10-01 03:51:22.831 E/Xposed (19395): at d.d.e.b.a(SourceFile:39)
10-01 03:51:22.831 E/Xposed (19395): at d.f.a.a(SourceFile:134)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.n$e.a(SourceFile:514)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.n$e.b(SourceFile:469)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.n$e.a(SourceFile:247)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.n$e.a(SourceFile:148)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.i$a.a(SourceFile:77)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.e$a.a(SourceFile:76)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.d$a.a(SourceFile:101)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.j$2.a(SourceFile:120)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.o$b.f(SourceFile:587)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.o$b.a(SourceFile:285)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.n$e.a(SourceFile:398)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.n$e.a(SourceFile:358)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.n$c.a(SourceFile:849)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.i$a.a(SourceFile:77)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.e$a.a(SourceFile:76)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.m$a.a(SourceFile:69)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.g$b.f(SourceFile:403)
10-01 03:51:22.831 E/Xposed (19395): at d.d.a.g$b.a(SourceFile:336)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.c.s.a(Unknown Source)
10-01 03:51:22.831 E/Xposed (19395): at d.d.e.b.a(SourceFile:39)
10-01 03:51:22.831 E/Xposed (19395): at d.f.a.a(SourceFile:134)
10-01 03:51:22.831 E/Xposed (19395): at com.b.b.c$a.a(SourceFile:208)
10-01 03:51:22.831 E/Xposed (19395): at com.b.b.a.a(SourceFile:47)
10-01 03:51:22.831 E/Xposed (19395): at com.b.b.d.a(SourceFile:84)
10-01 03:51:22.831 E/Xposed (19395): at com.b.b.e.a(SourceFile:20)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.c.m.a(SourceFile:70)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.c.k.b(SourceFile:105)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.c.d.a(SourceFile:99)
10-01 03:51:22.831 E/Xposed (19395): at com.icecream.snorlax.module.b.c.d.available(SourceFile:86)

**Comment by igoticecream** [comment]
Seems like you have got MISSINGNO pokemon id... Will take a look

**Comment by GeoWebDevCom** [comment]
To bad that xposed is detected again by Safety Net so i use just the root from superuser without xposed 😥

**Comment by igoticecream** [comment]
Yea, I have stopped the development of Snorlax until there's a fix.

**Comment by MaT-PT** [comment]
The latest suhide version (v0.54) makes it work again. :smiley_cat: 
Details here: https://www.reddit.com/r/pokemongodev/comments/56bqi8/new_suhide_v054_working_for_latest_safetynet/

**Comment by wjoshua1984** [comment]
Confirmed

**Comment by igoticecream** [comment]
Oh, I didn't know theres a bypass... wow that was fast.

So yea, I will continue the development of Snorlax

**Comment by igoticecream** [comment]
This is fixed on 1.3.0. Please confirm you got it working
