### ISSUE TITLE
Pattern to rename with mon's attack type

### ISSUE THREAD

**Issue by alexcheveau** [igoticecream/Snorlax#12]
Example: **STE-FIR 80% (20)**

In this example my pokemon got:
- Stell fast attack 
- Fire charge attack
- 80% IV 
- level 20

Bug     BUG
Dark        DAR
Dragon  DRA
Electric    ELE
Fairy       FAI
Fighting    FIG
Fire        FIR
Flying  FLY
Ghost   GHO
Grass   GRA
Ground  GRO
Ice     ICE
None    NON
Normal  NOR
Poison  POI
Psychic PSY
Rock        ROC
Steel       STE
Water   WAT

I don't know if it's possible to add something more fancy like symbols: thunder instead of a ELE

**Comment by igoticecream** [comment]
Yea sure... will add paterns

**Comment by FakeKitten** [comment]
You can compact it into 2 character patterns for each type like IVY used, originally from [this reddit thread](https://redd.it/4vcydv).
Bu, Da, Dr, El, Fa, Fi, Fr, Fl, Gh, Gr, Gd, Ic, No, Po, Ps, Ro, St, Wa

**Comment by igoticecream** [comment]
Implemented on commits:

95dbfa474a9962f4989fc319d3f80cbc071e71a5
6577738238e2dcc6b5fd30f2672e57933d9fbab8
fe63963307cc847689c4e472a26ecaa74a89569f

And is part of the 1.4.0 milestone
