### ISSUE TITLE
Great to see something coming along

### ISSUE THREAD

**Issue by wjoshua1984** [igoticecream/Snorlax#2]
Any plans to expand support? I'm sing Android N only? If not you may get alot about it not working especially when the xposed download doesn't mention it that I saw.

I just want to confirm this is just for notification of what it is, not an overlay like other modules that change nicknames? Correct? Either way glad somethings going and suggest moving in name changing direction with actual IV's.

**Comment by wjoshua1984** [comment]
K it's working was just took a few reboots maybe because I just switched to suhide for this. Just saw N support lol.

Anyhow if this changed nicknames it would do everything I would want, great job!

**Comment by igoticecream** [comment]
Its compiled with API 24, but it works for for API 19+

The nickname feature is planned for future releases
