### ISSUE TITLE
[BUG] Snorlax settings crashes/freeze if phone is locked.

### ISSUE THREAD

**Issue by FakeKitten** [igoticecream/Snorlax#20]
While making these issues on github my phone locked after checking the current settings in the module.

Turns out it messes up if the phone locks. [Would a pokeflute help?](https://puu.sh/rFJDT/fcc486d1e8.png)

**Comment by igoticecream** [comment]
Yea, v 1.4.0 will fix the issue... thanks you

Heres the fix commited

https://github.com/igoticecream/Snorlax/commit/2e8175e1dabf508a46ff8e47f60e6590e592f80b#diff-77884299e536aad81635e9d7d135f9edL61
