### ISSUE TITLE
Port to Magisk Manager 

### ISSUE THREAD

**Issue by riththerift** [igoticecream/Snorlax#27]
Hi there, 

With all the issue surrounding Xposed and Chainfire's  suhide, would it be possible to port this module to Magisk Manager?

**Comment by igoticecream** [comment]
Is magisk still capable of bypass xposed?

**Comment by riththerift** [comment]
I don't know. But it looks like Xposed can cause SafetyNet to fail so I was wondering if this Xposed module can be ported to Magisk as a module. If so it would remove the dependency on Xposed; you'll just have magisk and root. 

Please close this if this is not practical or pointless. 

Thanks

**Comment by wjoshua1984** [comment]
So magisk is a framework just like xposed that seems to be less vulnerable to safety net than xposed itself it may be worth a look. The last time fails occurred xposed seemed to be the common denominator. I haven't really had time to look at module templates but it's all laid out on git.

**Comment by igoticecream** [comment]
Magisk is a framework for systemless mods. Xposed is a framework that offers changing behavior of apps... two different framekworks.

Also, magisk cannot bypass safetynet
