### ISSUE TITLE
Small issue with the types (FIre vs FIght / GRass vs GRound)

### ISSUE THREAD

**Issue by alexcheveau** [igoticecream/Snorlax#28]
Originally Posted by MrGodMan (xda)
Small issue with the types;

You have the option to limit the types to a chosen length of characters but it simply clips the strings which means at 2 characters Fire and Fighting are the same as well as Ground and Grass. 
A simple fix for this is at 2 characters changing Fire to display as Fr and Ground to show as Gd as was suggested on some reddit thread and used in ivy.

Although this issue is very minimal as no pokemon I can think of that has ground and grass moves or fire and fighting which makes the move type clear from context.

**Comment by BoomEX-UK** [comment]
I understand this -- before using anything like Snorlax i tried manually tagging move types to the end of the names. I started with 1 letter, then with 2 and hit the same problems.

you're right it does sound small, but if you truly stick to 12char names then this would really help.
