### ISSUE TITLE
compability with pokemon go 0.37.0 and up

### ISSUE THREAD

**Issue by What-Zit-Tooya** [igoticecream/Snorlax#5]
how i can use this module since pokemon go 0.37.0 and up does not work if xposed installed?

**Comment by igoticecream** [comment]
I use chainfire's suhide to bypass xposed (which requires android 6.0+)

http://forum.xda-developers.com/apps/supersu/suhide-t3450396

**Comment by What-Zit-Tooya** [comment]
Its not working on my device, RR rom + cm13. Still can't play pokemon go.
You must create a step by step how to use it.
