### ISSUE TITLE
Payload validation failed

### ISSUE THREAD

**Issue by kelsony** [igoticecream/Snorlax#9]
hello friend, come tell something that happened to me, I do not know if it was by your module, but it happened so, I have a s5 with rom ressurection remix v5.7.4 day 23 using magisk migration method for suhide, installed your module and it worked perfect, turned off the function to detect the GPS soon after went to a website and I logged my account, the site was pogobag, compared iv and transfer some pokemons, log out and went pro game, worked regular, spent about 30 minutes not I was more into the game, I logged my account on the phone my wife and work, there on my phone I tested the application "SafetyNET for help" and was giving error "response payload validation failed", I had to reset my phone to voltata to work, however today took a sleep in the afternoon and when I woke up gave the same problem, and after a few minutes returned to work! I really want to use Snorlax module, but to give apprehending some new problem. I await your help

**Comment by igoticecream** [comment]
Sounds like SafetyNet is detecting xposed... I bypassed it with suhide.

Closing because is not related to Snorlax
